import { Chakra_Petch} from "next/font/google";
import "./globals.css";
import Header from "./components/Header";
import Footer from "./components/Footer";
import { Toaster } from "react-hot-toast";

const ChakraPetch = Chakra_Petch({
  weight: ['400','700'],
  style: ['normal'],
  subsets: ['latin'],
  display: 'swap',
})


export const metadata = {
  title: "File shering app",
  description: "Generated by mazaharul islam",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body className={ChakraPetch.className}>

   <Header/>
   <div className="px-4 py-2 mb-14">
        {children}
        <Toaster
        position="top-center"
        reverseOrder={false}
      />
        </div>
        <Footer/>


      </body>
    </html>
  );
}
